Archive: Add dynamic paths to browser tab
Next-Flip/Momentum-Firmware pull request #322
Opened 2024-12-15 21:03 UTC by 956MB

# What's new

Adds to the option to show current directory/path in archive tab instead of static tab text. Default state is `OFF` to maintain the existing look, but I personally think `Current` could probably be set as default if merged. Of course all text involed `Show Browser Path`, `Current`, `Brief` and `Full` could be changed as well.

- Adds setting under "Interface > File Browser > Show Browser Path" with four options:
  - Off (default): Shows static tab text like before (e.g. "Browser", "Sub-GHz", etc.)
  - Current: Shows the current directory name only (e.g. "Games")
  - Brief: Abbreviates the full path to the current directory (e.g. /e/a/Games")
  - Full: Shows complete path from root (e.g. "/ext/apps/Games")
- Path updates when navigating through directories. It is also maintained when opening an app and clicking back into the browser.
- Maintains existing header styling and layout keeping it within the frame
- Long paths that exceed the frame width are drawn with `elements_scrollable_text_line` to allow for full visibility.
    - e.g. Short paths like `Games` are drawn centered like normal, and long ones like `/ext/apps/Games` scroll.
    
## Screenshots

#### "Off"

<img width="528" alt="OFF" src="https://github.com/user-attachments/assets/4951fa20-2335-48a0-9a72-cde5a817f163" />

#### "Current"

<img width="528" alt="Current" src="https://github.com/user-attachments/assets/d6bac53f-3d04-4312-8b2f-f2cb80245a83" />

#### "Brief"

![Brief](https://github.com/user-attachments/assets/649aa595-3d22-4792-b9e3-83624d734f41)

#### "Full"

![Full](https://github.com/user-attachments/assets/cef5eeee-cf02-4d2a-815c-056ce90d6637)

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

2024-12-15 21:07 UTC, Willy-JL commented
*missed opportunity for `/e/a/Sports` in the brief example xD*

sorry i just had to :laughing:, i like this idea! will review in the coming days

2024-12-15 21:16 UTC, 956MB commented
> _missed opportunity for `/e/a/Sports` in the brief example xD_

AGH! Scrap the whole thing. Kidding, looking forward to it 👍

2025-01-17 00:17 UTC, 956MB commented on applications/main/archive/views/archive_browser_view.c
> +    size_t text_width = canvas_string_width(canvas, tab_name);
I just realized looking at this that checking the width and using canvas_draw_str_aligned isnt necessary because scrollable_text_line will function the same when it doesn't need to scroll.

2025-01-17 00:29 UTC, Willy-JL requested changes
small things, working on them rn

2025-01-17 00:29 UTC, Willy-JL commented on lib/momentum/settings.c
> +    {setting_bool(show_browser_path)},
using `setting_bool()` here will enforce the value is either 0 or 1, and save to file as "true" or "false". should be `setting_enum()`, which also specifies the max value (discards values that arent 0 to max-1). also since its a multiple option setting, could be renamed to `browser_path_mode` to match the enum.

2025-01-17 00:29 UTC, Willy-JL commented on applications/main/archive/views/archive_browser_view.c
> +    size_t text_width = canvas_string_width(canvas, tab_name);
yep :D

2025-01-17 00:29 UTC, Willy-JL commented on applications/main/archive/views/archive_browser_view.c
> +    if(!momentum_settings.show_browser_path || archive_is_home(browser)) {
here value 0 coincides with off, but being an enum (and also considering renaming the setting as before) its better to explicitly check against enum value

2025-01-17 00:29 UTC, Willy-JL commented on applications/main/archive/views/archive_browser_view.c
> +        default:
better to specify the enum value here too, in case there are more values added later, also makes it clearer

2025-01-17 00:29 UTC, Willy-JL commented on applications/main/archive/views/archive_browser_view.c
> +    furi_string_set(browser->prev_path, browser->path);
this doesn't seem to be used anywhere, lost between refactoring? ;)

2025-01-17 00:33 UTC, Willy-JL commented on applications/main/archive/views/archive_browser_view.c
> +    size_t text_width = canvas_string_width(canvas, tab_name);
actually no, if its shorter, then the scrollable text would align it to left instead of centered. however, there is a centered variant of the scrollable text function

2025-01-17 01:10 UTC, Willy-JL commented
hmm tho the way i did it makes it not change text while searching. just that the scrollable text text functions need a furistring so i thought to just use the same one as formatted path, but then for searching it needs to change even if the path didnt change. might be easier to just use a temporary furistring, or to use the normal draw function while searching

2025-01-17 01:20 UTC, Willy-JL approved these changes
nice :D

2025-01-17 01:44 UTC, merged